### PR TITLE
ISSUE 84 - add emacs to eri_python

### PR DESCRIPTION
**Pull request by enmyj**
addresses https://github.com/ElderResearch/gpu_docker/issues/84

### CODE REVIEW

**Comment by RZachLamberty** [comment]
this makes me so happy and so mad at the same time. profound internal dissonance.

**Comment by enmyj** [comment]
Think Joel will mind using `ed` instead of `emacs`? I can ask him.

**Comment by semperstew** [comment]
Nah. Just install it. There's no reason not to. I was just joking about the WON'T FIX.

**Comment by enmyj** [comment]
Shoot, I really wanted to see his face when I tried to make him use `ed` tho

**Comment by RZachLamberty** [comment]
`<serious>`actually you should not install emacs in the docker container; if he wants to edit files on the *machine* he should do it via `ssh` (if he's not aware of how to do this, point him [here](https://www.gnu.org/software/emacs/manual/html_node/emacs/Remote-Files.html)) and on the actual machine. install `emacs` on the machine and keep it out of the container`</serious>`

**Comment by semperstew** [comment]
> `<serious>`actually you should not install emacs in the docker container; if he wants to edit files on the _machine_ he should do it via `ssh` (if he's not aware of how to do this, point him [here](https://www.gnu.org/software/emacs/manual/html_node/emacs/Remote-Files.html)) and on the actual machine. install `emacs` on the machine and keep it out of the container`</serious>`

Other than cutting down on the size of the resulting image, what other advantages does this provide? To be clear, I support not having emacs in the image. I use VSCode in the same way.

**Comment by RZachLamberty** [comment]
reasons that affect everyone:
+ image size is one. enormous cost? not really. more worried about cumulative precedent there
+ resource usage. while `emacs` is not a particularly heavy process, it's still a separate process, stealing resources from the container and ultimately the base machine (and hence other users on that machine). the `emacs` user already has (or could easily have) an `emacs` process running on their own machine that accomplishes all their goals; use that.

reasons that affect the emacs user:
+ if you make your connections via `ssh` you don't have to lug your emacs settings around with you, which is an (again, very small, but not 0) extra storage cost on the gpu machine, and just a hassle
+ the ability to switch from local to remote file editing within the same emacs session is cleaner (imo) than switching windows / programs

**Pull request merged**
